common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['id_role', 'integer'],
            ['username', 'string'],
            ['email', 'unique'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @return array
     *
     * return all rights this user
     */
    public function getRights()
    {
        $fullRights = $this->getOpenedRights();

        foreach($this->getBanRights() AS $oneBanRight)
            if(isset($fullRights[$oneBanRight->id_right]))
                unset($fullRights[$oneBanRight->id_right]);

        return $fullRights;
    }

    /**
     * @return array
     *
     * return all opened rights (without ban-list)
     */
    public function getOpenedRights()
    {
        $fullRights = [];

        if($role = Roles::findOne($this->id_role))
            foreach($role->getRights() AS $oneRoleRight)
                $fullRights[$oneRoleRight->id] = $oneRoleRight;

        foreach(UserRights::find()->user($this->id)->all() AS $oneUserRight) {
            if($right = Rights::findOne($oneUserRight->id_right))
                $fullRights[$right->id] = $right;
        }

        return $fullRights;

    }

    /**
     * @return array|UserBanRights[]
     *
     * return ban rights
     */
    public function getBanRights()
    {
        return UserBanRights::find()->user($this->id)->all();
    }

    /**
     * @param $id_right
     * @return bool
     *
     * Check right
     */
    public function checkRight($id_right)
    {
        if(array_key_exists($id_right, $this->getRights()))
            return true;

        return false;
    }
}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use common\models\UserBanRights;
use common\models\UserRights;
use Yii;
use common\models\User;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\Rights;
use yii\helpers\ArrayHelper;
/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();



        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->saveRights($model->id);
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->saveRights($id);
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionGetOpenedRights($id_role)
    {
        if(!$id_role)
            return false;

        return $this->renderPartial('_open-rights', ['allRights' => Rights::find()->all(), 'selectedRights' => ArrayHelper::getColumn(Rights::find()->onRole($id_role)->all(), 'id')]);
    }

    protected function saveRights($id_user)
    {
        UserRights::deleteAll(['id_user' => $id_user]);
        //Save User Rights
        if(Yii::$app->request->post('open_right'))
            foreach(Yii::$app->request->post('open_right') AS $right) {
                $newUR = new UserRights();
                $newUR->id_right = $right;
                $newUR->id_user = $id_user;
                $newUR->save();
            }

        UserBanRights::deleteAll(['id_user' => $id_user]);

        //Save User Ban Rights
        if(Yii::$app->request->post('ban_right'))
            foreach(Yii::$app->request->post('ban_right') AS $right) {
                $newBR = new UserBanRights();
                $newBR->id_user = $id_user;
                $newBR->id_right = $right;
                $newBR->save();
            }
    }
}

frontend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\User;
use common\models\Roles;
use common\models\Rights;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput() ?>
    <?= $form->field($model, 'email')->textInput() ?>
    <?= $form->field($model, 'status')->dropDownList([User::STATUS_DELETED => 'Deleted', User::STATUS_ACTIVE => 'Active']) ?>
    <?= $form->field($model, 'id_role')->dropDownList(\yii\helpers\ArrayHelper::map(Roles::find()->all(), 'id', 'title'), ['prompt' => ' ---- Выберите роль']) ?>

    <b>Доступные права: </b><br>
    <div class="opened-rights" data-url="<?=\yii\helpers\Url::toRoute('user/get-opened-rights')?>">
        <?=$this->render('_open-rights', ['allRights' => Rights::find()->all(), 'selectedRights' => ArrayHelper::getColumn($model->getOpenedRights(), 'id')])?>
    </div>

    <br>

    <b>Запретить пользователю: </b><br>
    <?php foreach(Rights::find()->all() AS $oneRight) { ?>
        <input name="ban_right[<?=$oneRight->id?>]" type="checkbox" value="<?=$oneRight->id?>" <?=(in_array($oneRight->id, ArrayHelper::getColumn($model->getBanRights(), 'id_right'))) ? 'checked="checked"' : ''?>><?=$oneRight->description?><br>
    <?php } ?>

    <br>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/user/_open-rights.php
<?php
use yii\helpers\ArrayHelper;
?>
<?php foreach($allRights AS $oneRight) { ?>
    <input name="open_right[<?=$oneRight->id?>]" type="checkbox" value="<?=$oneRight->id?>" <?=(in_array($oneRight->id, $selectedRights)) ? 'checked="checked"' : ''?>>
    <?=$oneRight->description?>
    <br>
<?php } ?>

frontend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            'username',
//            'auth_key',
//            'password_hash',
//            'password_reset_token',
            [
                'attribute' => 'id_role',
                'content' => function($data) {
                    if($role = \common\models\Roles::findOne($data->id_role))
                        return $role->title;

                    return 'Undefined';
                }
            ],
            [
                'attribute' => 'rights',
                'content' => function($data) {
                    $html = '';
                    foreach($data->getRights() AS $one) {
                        $html .= $one->description . '<br>';
                    }

                    return $html;
                }
            ],
             'email:email',
            // 'status',
            // 'created_at',
            // 'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

frontend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'email:email',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>